name: Build-All

on:
  workflow_dispatch:

jobs:
  immortalwrt:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Trigger ImmortalWrt
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-ImmortalWrt

  openwrt:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Trigger OpenWrt
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-OpenWrt

  lede:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Trigger LEDE
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-LEDE
