name: Build-All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: ImmortalWrt 18.06 K5.4
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: N1-ImmortalWrt-18.06-K5.4

    - name: ImmortalWrt 23.05
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: N1-ImmortalWrt-23.05

    - name: LEDE
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: N1-LEDE

    - name: OpenWrt 23.05
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: N1-OpenWrt-23.05

    - name: IStoreOS
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        event-type: N1-iStoreOS
