name: Build-All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: ImmortalWrt
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-ImmortalWrt

    - name: OpenWrt
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-OpenWrt

    - name: LEDE
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-LEDE
