name: Build-All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: ImmortalWrt 24.10
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-ImmortalWrt24.10

    - name: ImmortalWrt 23.05
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        event-type: N1-ImmortalWrt23.05
